# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vA08moCFHhIT7wbnfpd05lrbJwuqKQSP
"""

#!pip install streamlit
from fastai.vision import *
from torch.jit.annotations import Optional
import pickle
import streamlit as st

MODEL_URL = "https://github.com/nikhilreddybilla28/pets-oxford-iiit/raw/master/export.pkl"
urllib.request.urlretrieve(MODEL_URL, "model.pkl")
path = Path(".")

learner = load_learner(path, "model.pkl")

def predic(img):
  pred_class,_,probs = learner.predict(img)
  print(pred_class)
  #prob = max(probs)
  return pred_class 

def main():
    st.title("Pet Breed Classifier")
    html_temp = """
    <div style="background-color:tomato;padding:12px">
    <h2 style="color:white;text-align:center;"> Bredd classifier App </h2>
    </div>
    """
    st.markdown(html_temp,unsafe_allow_html=True)
    img = st.file_uploader("Choose an image...", type="jpg")
    if img is not None:
      st.image(image, caption='Uploaded Image.', use_column_width=True)
      st.write("")
      st.write("Classifying...")
      result=" "
      if st.button("Predict"):
        result = predic(img)
      st.success('The output is {}'.format(result))

if __name__=='__main__':
    main()
