# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vA08moCFHhIT7wbnfpd05lrbJwuqKQSP
"""

#!pip install streamlit

from fastai.basic_train import load_learner
import pickle
import streamlit as st

classifier=  load_learner('https://github.com/nikhilreddybilla28/pets-oxford-iiit/blob/master/export.pkl')

def predict(img):
  pred=classifier.predict(img)
  print(pred[0])
  return pred[0]

def main():
    st.title("Pet Breed Classifier")
    html_temp = """
    <div style="background-color:tomato;padding:12px">
    <h2 style="color:white;text-align:center;"> Bredd classifier App </h2>
    </div>
    """
    st.markdown(html_temp,unsafe_allow_html=True)
    img = st.file_uploader("Choose an image...", type="jpg")
    if img is not None:
      st.image(image, caption='Uploaded Image.', use_column_width=True)
      st.write("")
      st.write("Classifying...")
      result=" "
      if st.button("Predict"):
        result=predict(img)
      st.success('The output is {}'.format(result))

if __name__=='__main__':
    main()
